import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

import { UserDetailProvider } from "./provider";
import { ClerkProvider } from "@clerk/nextjs";
import ConvexClientProvider from "./ConvexClientProvider";

export const metadata: Metadata = {
  title: "VoyageAI: Personalized AI Trip Planner",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

const manrope = Manrope({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={manrope.className}>
          <ConvexClientProvider>
            <UserDetailProvider>
              {children}
            </UserDetailProvider>
          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}